### ISSUE TITLE
Images don't render in copied Colab notebooks

### ISSUE THREAD

**Issue by MaxGhenis** [aamini/introtodeeplearning#23]
The images in the notebooks go to relative links from the folder structure. This works when rendering in GitHub, but not in Colab. For example, from [lab1/Part1_tensorflow.ipynb](https://github.com/aamini/introtodeeplearning_labs/blob/master/lab1/Part1_tensorflow.ipynb):

    ...
    ![alt text](img/add-graph.png "Computation Graph")
![image](https://user-images.githubusercontent.com/6076111/54006296-96194a00-4111-11e9-98d9-5c1a0b94dd23.png)

This can be fixed by pulling in the image path from the web, e.g.:

    ...
    ![alt text](https://github.com/aamini/introtodeeplearning_labs/raw/master/lab1/img/add-graph.png "Computation Graph")

![image](https://user-images.githubusercontent.com/6076111/54006334-b8ab6300-4111-11e9-8794-6f2485a5b1d3.png)

Adding the `https://github.com/aamini/introtodeeplearning_labs/raw/master/lab1/` (or `lab2` etc.) prefix to images' path in the notebook will ensure they render in both GitHub and Colab.

**Comment by MaxGhenis** [comment]
Rather, this only happens when copying a Colab notebook. This isn't necessary but I find it helpful to save a copy with my own edits. Updated title accordingly.

**Comment by aamini** [comment]
Great suggestion, we've (hopefully) fixed this!
