### ISSUE TITLE
Colab makes indented text red because it expects four spaces by default

### ISSUE THREAD

**Issue by MaxGhenis** [aamini/introtodeeplearning#24]
Probably too minor to mention, but just wanted to point out in case people notice it: since the notebooks indent with two spaces and Colab expects four spaces by default, Colab will make indented text red as a warning. e.g. from [lab1/Part1_tensorflow.ipynb](https://github.com/aamini/introtodeeplearning_labs/blob/master/lab1/Part1_tensorflow.ipynb):

![image](https://user-images.githubusercontent.com/6076111/54006751-800c8900-4113-11e9-99a1-f40898f6300f.png)

Setting the indentation width to 2 spaces fixes this (Tools...Preferences...Indentation width in spaces):
![image](https://user-images.githubusercontent.com/6076111/54006649-11c7c680-4113-11e9-8278-b28a8009559d.png)

No more warning:
![image](https://user-images.githubusercontent.com/6076111/54006767-8bf84b00-4113-11e9-9ccf-64ab81c4bf91.png)

**Comment by apsoleimany** [comment]
thanks for pointing this out! indentation width is set to 2 in all of the most updated notebooks and will also be for the forthcoming 2021 version.
