### ISSUE TITLE
Avoid colocate_with warning in lab1/part1 solution by using tf.add

### ISSUE THREAD

**Issue by MaxGhenis** [aamini/introtodeeplearning#25]
[lab1/Part1_tensorflow_solution.ipynb](https://github.com/aamini/introtodeeplearning_labs/blob/master/lab1/Part1_tensorflow_solution.ipynb) includes this code:
```
def our_dense_layer(x, n_in, n_out):
  # ...
  z = tf.matmul(x,W) + b
```

When this is called in the next cell, it produces this warning:
```
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:642: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
tf.Tensor([[0.95257413 0.95257413 0.95257413]], shape=(1, 3), dtype=float32)
```

This warning can be avoided by replacing the `+b` code segment with `tf.add`, i.e.

    z = tf.add(tf.matmul(x, W), b, name="z")

(also more TensorFlow-y)

**Comment by hemusqwerty** [comment]
wx=tf.Variable(tf.random_normal(shape=[num_inputs,num_neurons]))

how to remove this warning 
WARNING:tensorflow:From /home/mongrel/.virtualenvs/openCV/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.

**Comment by iperov** [comment]
```
import tensorflow as tf      
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)
```

**Comment by aamini** [comment]
Thanks, this has been fixed now
