### ISSUE TITLE
Lab1/Part2_debiasing_solution.ipynb fails with TypeError

### ISSUE THREAD

**Issue by TitanTomorrow** [aamini/introtodeeplearning#27]
When executing  "encoder_output = encoder(inputs)" (search for exact phrase), it fails with a type error:
TypeError: Failed to convert object of type <type 'tuple'> to Tensor. Contents: (Dimension(None), Dimension(100)). Consider casting elements to a supported type.

I'm using colab and following the recommended solution.

I propose
"epsilon = tf.random_normal(shape=(batch, dim))" be replaced with
"epsilon = tf.random_normal(shape=tf.shape(z_mean))"

I followed the remainder of the lab and got something that made sense.

**Comment by stoufa** [comment]
I had the same problem, and replacing `(batch, dim)` with `tf.shape(z_mean)` solved it, thanks for sharing.
You should create a new pull request.

**Comment by aamini** [comment]
Thanks, this should be fixed now. Please checkout the new lab2 version.
