### ISSUE TITLE
Lab3, part 2 pong will not save video correctly

### ISSUE THREAD

**Issue by TitanTomorrow** [aamini/introtodeeplearning#28]
"**save_video_of_model(pong_model, "Pong-v0", filename='pong_agent.mp4')**" will fail because

**save_video_of_model** does not call pre_process on the observations, the model expects a pre-processed tensor of size 80*80 and not the raw one that comes from the Pong-v0. 

as a hack, I changed (just for the pong model)
`action = model(tf.convert_to_tensor(obs.reshape((1,-1)), tf.float32)).numpy().argmax()`
to
`action = model(tf.convert_to_tensor(pre_process(obs).reshape((1,-1)), tf.float32)).numpy().argmax()
`

**Comment by stoufa** [comment]
Thanks for sharing :+1:

**Comment by aamini** [comment]
Thanks, this should be fixed now. Please checkout the lab3 branch or master in about 1 day when we merge in that PR for the new 2020 version of this course.
