### ISSUE TITLE
Error while importing util

### ISSUE THREAD

**Issue by SarthakSG** [aamini/introtodeeplearning#36]
I'm getting this error in most of the notebooks.
Stacktrace in Colab ->

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-a35ad9abfcc1> in <module>()
     14 
     15 # Import the necessary class-specific utility files for this lab
---> 16 import introtodeeplearning_labs as util

/content/introtodeeplearning_labs/__init__.py in <module>()
----> 1 from lab1 import *
      2 from lab2 import *
      3 # from lab3 import *
      4 
      5 

ModuleNotFoundError: No module named 'lab1'

**Comment by Choapinus** [comment]
I changed
`import introtodeeplearning_labs as util`
with
`import util`
and it works fine :)

Ps: the file is for python 2.x, put the parentheses in the prints (lines 10, 31, 38) only if you are using python 3.x

**Comment by 1pk73** [comment]
Now it says no module named util. Can you please tell us why is this happening?

**Comment by PGhai** [comment]
Install regex using pip command, it will solve the error.

!pip install regex

**Comment by swag94** [comment]
> Install regex using pip command, it will solve the error.
> 
> !pip install regex

This is also not working. Now i am getting error in __init__.py showing that ModuleNotFoundError: No module named 'lab1' while importing lab1.

**Comment by aamini** [comment]
Thanks for raising these errors, please checkout the new version of the repo. This error should be fixed now with the inclusion of our new `mitdeeplearning` package.
