### ISSUE TITLE
ModuleNotFoundError: No module named 'lab1'

### ISSUE THREAD

**Issue by IngridJSJ** [aamini/introtodeeplearning#42]
Hi, quick solution for importing this modules? 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-13ec8f997e10> in <module>()
      8 from IPython import display as ipythondisplay
      9 
---> 10 import introtodeeplearning_labs as util
     11 
     12 is_correct_tf_version = '1.14.0' in tf.__version__

/content/introtodeeplearning_labs/__init__.py in <module>()
----> 1 from lab1 import *
      2 from lab2 import *
      3 # from lab3 import *
      4 
      5

**Comment by WizardOfAus** [comment]
It is not recognising the folder lab1 and so not importing it directly. I had this issue as well, just find the functions you need and apply them directly.

**Comment by mbellezi** [comment]
change introtodeeplearning_labs/__init__.py:

from .lab1 import *
from .lab2 import *


change lab1/__init__.py  and  lab2/__init__.py:

from .util import *

**Comment by aamini** [comment]
Thanks for raising this point. We've fixed this in the new version of the course. Lab 1 updated in master now, labs 2 and 3 will be up over the next couple days.
