### ISSUE TITLE
Need information!!!

### ISSUE THREAD

**Issue by parulgarg123** [aamini/introtodeeplearning#51]
Why we imported `from tensorflow.keras import Model`
Doesn't correlate what's the significance.

@aamini @dwanderton @aravic @apsoleimany 

<img width="868" alt="Screenshot 2020-02-29 at 5 59 01 PM" src="https://user-images.githubusercontent.com/30907440/75607445-45b6ab80-5b1d-11ea-8c5e-7d912c23c205.png">

**Comment by aamini** [comment]
`tf.keras.Model` is used on line 6, but yes you are right should just be inherriting from the shortcut `Model` instead of the full path to the module.
