### ISSUE TITLE
Lab1 Part2 returns "Found 0 songs in text" after training the model

### ISSUE THREAD

**Issue by Guidogl** [aamini/introtodeeplearning#62]
Hello, 

I have tried to recreate Lab1 Music Generation with RNNs and I got "Found 0 songs in text" after running the last piece of code.

At first, I thought that it is my fault but then I just copied all the solution code and still got that message. 

Any ideas how to fix it?

**Comment by porwal97** [comment]
Hey!
I was facing the same problem. I raised a doubt on Twitter and received [This] (https://twitter.com/mitdeeplearning/status/1245441225076772864?s=21) reply. 

My issue got resolved by just increasing the units to 2048. And training the model for a longer duration. 

Hope it helps :)

**Comment by Guidogl** [comment]
Setting rnn_units to 2048 worked fine. Thanks!
