### ISSUE TITLE
can't play music though no error occurs

### ISSUE THREAD

**Issue by creater-yzl** [aamini/introtodeeplearning#66]
I ran the code below with colab, but I didn't hear a sound.
!pip install mitdeeplearning
import mitdeeplearning as mdl

songs = mdl.lab1.load_training_data()
example_song = songs[0]
mdl.lab1.play_song(example_song)

**Comment by creater-yzl** [comment]
I tried and it has no response either in anaconda or colab. I think I have awaited long enough

**Comment by VincentChungHeiPoon** [comment]
I know it's late but try to run it on google colab, I was having the same issue with Jupiter notebook on my computer.

**Comment by creater-yzl** [comment]
Thank you very much, it's OK now. I applied exactly the same steps as last time, but it works this time. quite strange

**Comment by rauf-source** [comment]
I tried running on google colab, kaggle.. on different browsers.. didn't work. It worked once on google colab, but when I tried to run it again it never did. : ( I think I'm figure it out soon, I hope XD

**Comment by pabramowitsch** [comment]
A couple of years have passed, but the problem persists.  In fact no valid songs are generated, even by the unmodified solution notebook running in COLAB.  When I print out the "generated songs" there's no evidence of any training beyond being able to append a ":" after the initial X.  The rest is just garbage.    Does anyone have a solution?
