### ISSUE TITLE
equation not rendered

### ISSUE THREAD

**Issue by drdozer** [aamini/introtodeeplearning#72]
In lab2/Part2_Debiasing.ipynb, when viewed through github, the equations for vae_loss_function are not rendered as latex. They appear as the raw latex strings.

**Comment by apsoleimany** [comment]
Thank you for pointing this out. This has been corrected and will be pushed in the forthcoming 2021 version. Please see commit: efcbcc860c31404bc978ca02862dc9ca6df4598a on the current 2021 branch, soon to be merged into master.
