### ISSUE TITLE
extract_song_snippet function has a flaw

### ISSUE THREAD

**Issue by abc123yuanrui** [aamini/introtodeeplearning#76]
The pattern '\n\n(.*?)\n\n' can't extract the first song and the last song (if full generated), since we use start string 'X' rather than '\n\nX'

**Comment by gcervantes2005** [comment]
See https://github.com/aamini/introtodeeplearning/issues/62 maybe the generated text is not a valid song

**Comment by abc123yuanrui** [comment]
> See #62 maybe the generated text is not a valid song

Thanks for the reply, but my previous comment explained the reason why this issue would happen. To be more concrete, the extract_song_snippet function omit the first song no matter it's valid or not, since the first song always start with 'X'. I replaced it with my own function (or you can simply replace the 'n\n(.*?)\n\n' with 'X:(.*?)\n\n' in the function), and it extracts the first song. The first song is playable in my case, plus the play_song function would do the validation afterwards. Unfortunately I can't&should't make direct change on this project so I leave it as an issue here.

**Comment by gcervantes2005** [comment]
Ohh sorry I see your point, as a test I added

generated_text = "\n\n" + generated_text+"\n\n"

on the "Play back the generated music!" section and found the other songs.

Will make the adjustment you recommended in my code, thanks!

**Comment by abc123yuanrui** [comment]
> Ohh sorry I see your point, as a test I added
> 
> generated_text = "\n\n" + generated_text+"\n\n"
> 
> on the "Play back the generated music!" section and found the other songs.
> 
> Will make the adjustment you recommended in my code, thanks!

No problem! I think what you did is a good and easier way for us to test this issue instead of making changes to the function :)

**Comment by aamini** [comment]
Thanks -- this is definitely an issue and we'll make sure it's fixed for the next course iteration. Leaving this issue open until then (or until there is a PR to address it).

**Comment by apsoleimany** [comment]
thank you! this issue has been fixed for 2021, which will be merged into the master branch this week.
