### ISSUE TITLE
Lab 2 Part 2 training data not accessible

### ISSUE THREAD

**Issue by dgutschick** [aamini/introtodeeplearning#79]
The dropbox link in the code below gives a 404 error now, although it was fine earlier today (2020 07 28)

# Get the training data: both images from CelebA and ImageNet
path_to_training_data = tf.keras.utils.get_file('train_face.h5', 'https://www.dropbox.com/s/l5iqduhe0gwxumq/train_face.h5?dl=1')
# Instantiate a TrainingDatasetLoader using the downloaded dataset
loader = mdl.lab2.TrainingDatasetLoader(path_to_training_data)

**Comment by aamini** [comment]
Very strange. I have no idea what caused this but am also having the same issue. I'm recreating the file and will fix it soon. In the meantime if you need a quick and dirty fix you might have a backed up version available (from a previous run) in your `~/.keras/datasets` folder that you can use directly.

**Comment by aamini** [comment]
Thanks for raising this issue. I've addressed it in commits 6e783269 and c89db136. Please let me know if you have any further issues.
