### ISSUE TITLE
For lab2, https://www.dropbox.com/s/bp54q547mfg15ze/train_face.h5?dl=1 link not found

### ISSUE THREAD

**Issue by ayaartist** [aamini/introtodeeplearning#81]
For lab2, I got 404 link not found for the dropbox link in the title. Is there something wrong with the URL link? Thank you so much!

**Comment by aamini** [comment]
I also got a 404 error, but then tried again and now it works. I'm not sure why it was not working before but I'm looking into it -- please let me know if you experience the problem again as it might be related to #79. 

Closing for now, but please reopen if the 404 comes back.

**Comment by ayaartist** [comment]
Hi Amini, I don't think it's working still. It never worked for me either...

**Comment by ayaartist** [comment]
Sorry sorry please ignore my previous comment. It's working now! Thank you very much!

**Comment by aamini** [comment]
It looks like the problem with Dropbox is back (as reported by #82)... As a temporary fix, if you still need access but are having 404 errors, please try replacing the URL with (https://www.dropbox.com/s/hlz8atheyozp1yx/train_face.h5?dl=1) on your local notebook. In the meantime, I will look into why this is occurring and properly fix it ASAP.
