### ISSUE TITLE
[Lab 2 / Part 2] Training dataset is missing

### ISSUE THREAD

**Issue by vivianliang** [aamini/introtodeeplearning#82]
Regarding Section 2.2 of **Lab2, Part2 - Debiasing**, the training data hosted at https://www.dropbox.com/s/dl/bp54q547mfg15ze/train_face.h5 no longer exists. Thanks for the great class!

**Comment by aamini** [comment]
Apologies, Dropbox seems to be having some strange issues hosting this data... some other people also cannot access the data even though it was briefly back online earlier today (#81) and (#79). 

As a temporary fix, can you please try replacing the URL with (https://www.dropbox.com/s/hlz8atheyozp1yx/train_face.h5?dl=1) on your local notebook? I will look into why this is occurring and properly fix it ASAP.

**Comment by vivianliang** [comment]
Thank you!

**Comment by shravankumar147** [comment]
This is working 

[lab2 faces dataset](https://www.dropbox.com/s/hlz8atheyozp1yx/train_face.h5?dl=1)

Thanks @aamini
