### ISSUE TITLE
Lab sessions 4 and 5 of the course

### ISSUE THREAD

**Issue by ShivamSRS** [aamini/introtodeeplearning#83]
Thanks a lot for this great course ! But could you also please make lab sessions 4 and 5 available at github? I'll highly appreciate it, much thanks!

**Comment by MikolajKolman** [comment]
Lab sessions 4 and 5 are for final projects of the students there, that were described in the first lecture. I dont think there is anything to share with us.

**Comment by aamini** [comment]
Correct, there are no lab sessions for 4 and 5. Those days were devoted to final projects.
