### ISSUE TITLE
module 'mitdeeplearning.lab3' has no attribute 'pong_change'

### ISSUE THREAD

**Issue by mohlondon** [aamini/introtodeeplearning#92]
I'm doing the pong part of RL Lab I ran into this issue i've tried looking into all versions of mitdeeplearning i didn't find pong_change function can you fix this

**Comment by aamini** [comment]
This should be available in the current (and latest) version of MDL. Here is a pointer to the exact location: https://github.com/aamini/introtodeeplearning/blob/1fae3136f01b12c93b182c30599c93285ffeb38f/mitdeeplearning/lab3.py#L30

**Comment by mohlondon** [comment]
yes thank you
